name: "Check PR"

on:
  pull_request:
  push:
    branches:
      - main
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Check_Format:
    name: "Check Formatting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install mise
        uses: jdx/mise-action@v2
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2.7.3
      - name: "Check Format"
        run: cargo fmt --check

  Check_Lint:
    name: "Check Linting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install mise
        uses: jdx/mise-action@v2
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2.7.3
      - name: "Run Clippy"
        run: cargo clippy --all-targets --all-features -- -D warnings

  Check_Build:
    name: "Check Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install mise
        uses: jdx/mise-action@v2
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2.7.3
      - name: "Build Contract (Optimized)"
        run: cargo build --locked --profile release --target wasm32-unknown-unknown

  Check_Tests:
    name: "Run Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install mise
        uses: jdx/mise-action@v2
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2.7.3
      - name: "Run All Tests"
        run: cargo test --lib --verbose
